/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RatingRouteImport } from './routes/rating'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TrackingRouteImport } from './routes/tracking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRoute = RatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/driver': typeof DriverRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/rating': typeof RatingRoute
  '/search': typeof SearchRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/driver': typeof DriverRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/rating': typeof RatingRoute
  '/search': typeof SearchRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/driver': typeof DriverRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/rating': typeof RatingRoute
  '/search': typeof SearchRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking'
    | '/driver'
    | '/history'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/payment'
    | '/profile'
    | '/rating'
    | '/search'
    | '/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/booking'
    | '/driver'
    | '/history'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/payment'
    | '/profile'
    | '/rating'
    | '/search'
    | '/tracking'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking'
    | '/driver'
    | '/history'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/payment'
    | '/profile'
    | '/rating'
    | '/search'
    | '/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingRoute: typeof BookingRoute
  DriverRoute: typeof DriverRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  RatingRoute: typeof RatingRoute
  SearchRoute: typeof SearchRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating': {
      id: '/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingRoute: BookingRoute,
  DriverRoute: DriverRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  RatingRoute: RatingRoute,
  SearchRoute: SearchRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
